version: '3'

services:
  database:
    image: postgres:12
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - /data/postgres
    ports:
      - '5432:5432'
